
BASE_MODEL = "cagliostrolab/animagine-xl-3.1"
LORA = "SungjinWi/INU_MASCOTT"

PROMPT_PREFIX = '1boy, "TOK", '
PROMPT_POSTFIX = ''
NEG_PROMPT = "nsfw, lowres, (bad), error, fewer, extra, missing, worst quality, low quality, unfinished, displeasing,"
RESULT_DIR = "./server_outputs"
BATCH_SIZE = 2

PORT = 5000
NGROK_HOSTNAME = "YOUR_NGROK_DOMAIN"
