
BASE_MODEL = "cagliostrolab/animagine-xl-3.1"
LORA = "/home/aidml/sjwi/INU_MASCOTT/train_results/INU_animagineV_3_1.safetensors"
PROMPT_SAFETY_CHECKER = "ezb/NSFW-Prompt-Detector"

PROMPT_PREFIX = '1boy, "TOK", blue hair, '
PROMPT_POSTFIX = ', very aesthetic, masterpiece'
NEG_PROMPT = "nsfw, nude, lowres, bad, error, fewer, extra, missing, worst quality, low quality, bad anatomy, unfinished, displeasing, watermark"
RESULT_DIR = "./server_outputs"
BATCH_SIZE = 1

PORT = 5000
NGROK_HOSTNAME = "inumascott.ngrok.dev"
